# Generated by Django 4.0.4 on 2022-06-15 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoDiuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 8, 54, 18, 269196)),
        ),
    ]
