# Generated by Django 4.0.4 on 2022-06-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoDiuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cita_fecha',
            field=models.DateField(blank=True),
        ),
    ]
