# Generated by Django 4.0.4 on 2022-06-15 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoDiuApp', '0002_alter_user_fecharegistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 11, 50, 44, 456294)),
        ),
    ]
