# Generated by Django 4.0.5 on 2022-06-15 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoDiuApp', '0003_alter_user_fecharegistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cita_fecha',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 9, 2, 35, 211546)),
        ),
    ]
